# Generated by Django 4.1.1 on 2022-09-21 10:35

from django.db import migrations, models

def forward(apps, schema_editor):
    Student = apps.get_model('school','Student')
    for student in Student.objects.all():
        student.teachers.add(student.teacher)

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_group_alter_student_name_and_more'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
